### PR TITLE
Add enable option so faker can be used in production

### PR DESCRIPTION
**Pull request by samselikoff**
Thanks for this addon! I'm using it to generate some mock data, and I've been deploying my app with all the mocks enabled to demo it to stakeholders. That's the motivation for being able to use faker in production environments.

### CODE REVIEW

**Comment by johnotander** [comment]
Thanks!

**Comment by johnotander** [comment]
Published to npm as `ember-faker@1.1.0`.

**Comment by samselikoff** [comment]
did you publish to npm? im getting a version not found error

**Comment by johnotander** [comment]
Sorry about that, pushed the git tags but forgot to publish to npm. It's now published.

**Comment by samselikoff** [comment]
great, thanks mate!

**Pull request merged**
